### ISSUE TITLE
format error

### ISSUE THREAD

**Issue by tobiasfiechter** [yangxuan8282/docker-image#2]
Hey!

I tried to fork your repository to check out the resilio container. When I pull your image directly through docker pull docker pull yangxuan8282/rpi-resilio-sync everything seems to work. But when I try using the forked image from https://hub.docker.com/r/cyberto/rpi-resilio-sync/ I get 
`standard_init_linux.go:178: exec user process caused "exec format error"`

It looks like I used the wrong base image, but I think I'm using a armhf image which should work propperly!

I'm new to docker, maybe you could help me or describe how you made it work

**Comment by tobiasfiechter** [comment]
Okay I think the problem is, that I made an automated build on docker hub and it can only build x86 images. So when I try to clone the repo to my raspberry and execute docker build . and then run the image I get an 
`Error relocating /usr/bin/rslsync: mallopt: symbol not found`

**Comment by yangxuan8282** [comment]
I can confirm that, sorry for not test before push image. I think the issue maybe caused by  2.5.2 not work with libc6-compat. And I'm trying to compile glibc with [sgerrand/alpine-pkg-glibc](https://github.com/sgerrand/alpine-pkg-glibc), hope it will work, and it will take time.

**Comment by yangxuan8282** [comment]
although I didn't success compile glibc myself, but I found pre-built version glibc from [armhf-docker-library/alpine-pkg-glibc](https://github.com/armhf-docker-library/alpine-pkg-glibc/releases). and I use it build an armhf alpine glibc image.
the latest tag on docker hub should work now, I have test it on raspberry pi 3.

**Comment by tobiasfiechter** [comment]
You are fantastic! It works perfectly
