### ISSUE TITLE
[rpi-resilio-sync] Device name will not be saved

### ISSUE THREAD

**Issue by screendriver** [yangxuan8282/docker-image#4]
When I setup everything and enter a device name at the beginning, the name will be ignored. Instead a cryptic name like `fa91ba8b79c5` will be generated.

**Comment by yangxuan8282** [comment]
That string is your resilio sync container ID. I don't really know how to change it, maybe you can ask resilio sync support for help.

**Comment by screendriver** [comment]
Ok, I will do that. Thanks :+1:
